services:
  - type: web
    name: biteroute-backend
    runtime: python
    rootDir: backend/biteroute_backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn biteroute_backend.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: ADMIN_EMAIL
        value: "admin@1234.com"
      - key: ADMIN_PASSWORD
        value: "admin123"
